apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: knative-serving-resources
  namespace: knative-serving
spec:
  resourceSelectors:
    # Knative Serving Core Components
    - apiVersion: v1
      kind: Namespace
      name: knative-serving
    - apiVersion: v1
      kind: ServiceAccount
      name: controller
      namespace: knative-serving
    - apiVersion: v1
      kind: ServiceAccount
      name: autoscaler
      namespace: knative-serving
    - apiVersion: v1
      kind: ConfigMap
      name: config-autoscaler
      namespace: knative-serving
    - apiVersion: v1
      kind: ConfigMap
      name: config-network
      namespace: knative-serving

    # Knative Serving Deployments
    - apiVersion: apps/v1
      kind: Deployment
      name: activator
      namespace: knative-serving
    - apiVersion: apps/v1
      kind: Deployment
      name: autoscaler
      namespace: knative-serving
    - apiVersion: apps/v1
      kind: Deployment
      name: controller
      namespace: knative-serving
    - apiVersion: apps/v1
      kind: Deployment
      name: webhook
      namespace: knative-serving

    # Knative Serving Services
    - apiVersion: v1
      kind: Service
      name: activator-service
      namespace: knative-serving
    - apiVersion: v1
      kind: Service
      name: webhook
      namespace: knative-serving

  placement:
    clusterAffinity:
      clusterNames:
        - member1
    spreadConstraints:
      - maxGroups: 1
        minGroups: 1
        spreadByField: cluster
  propagationMode: BidirectionalSync
