apiVersion: policy.karmada.io/v1alpha1
kind: ClusterPropagationPolicy
metadata:
  name: argo-workflows-cluster-resources
spec:
  resourceSelectors:
    # CRDs
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: clusterworkflowtemplates.argoproj.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: cronworkflows.argoproj.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: workflowartifactgctasks.argoproj.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: workfloweventbindings.argoproj.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: workflows.argoproj.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: workflowtasksets.argoproj.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: workflowtemplates.argoproj.io
    # Cluster-level RBAC
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      name: argo-cluster-role
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      name: argo-server-cluster-role
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      name: argo-aggregate-to-admin
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      name: argo-aggregate-to-edit
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      name: argo-aggregate-to-view
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      name: argo-binding
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      name: argo-server-binding
  placement:
    clusterAffinity:
      clusterNames:
        - member1
  propagationMode: BidirectionalSync
