apiVersion: policy.karmada.io/v1alpha1
kind: ClusterPropagationPolicy
metadata:
  name: argo-workflows-cluster-resources
spec:
  resourceSelectors:
    # Argo Workflows CRDs (필수)
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: clusterworkflowtemplates.argoproj.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: cronworkflows.argoproj.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: workflowartifactgctasks.argoproj.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: workfloweventbindings.argoproj.io

    # Cluster Role 및 Cluster Role Binding (RBAC)
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      name: argo-workflows-role
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      name: argo-workflows-webhook
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      name: argo-workflows-binding
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      name: argo-workflows-webhook-binding

  placement:
    clusterAffinity:
      clusterNames:
        - member1
  propagationMode: BidirectionalSync
