apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: argo-workflows-resources
  namespace: argo
spec:
  resourceSelectors:
    # ServiceAccounts (유지)
    - apiVersion: v1
      kind: ServiceAccount
      name: argo
      namespace: argo
    - apiVersion: v1
      kind: ServiceAccount
      name: argo-server
      namespace: argo
    - apiVersion: v1
      kind: ServiceAccount
      name: github.com
      namespace: argo
    
    # ConfigMaps (유지)
    - apiVersion: v1
      kind: ConfigMap
      name: workflow-controller-configmap
      namespace: argo
    - apiVersion: v1
      kind: ConfigMap
      name: artifact-repositories
      namespace: argo

    # Secrets (유지)
    - apiVersion: v1
      kind: Secret
      name: argo-server-sso
      namespace: argo
    - apiVersion: v1
      kind: Secret
      name: argo-workflows-webhook-clients
      namespace: argo
    - apiVersion: v1
      kind: Secret
      name: my-minio-cred
      namespace: argo

    # Services (유지)
    - apiVersion: v1
      kind: Service
      name: argo-server
      namespace: argo
    - apiVersion: v1
      kind: Service
      name: minio
      namespace: argo
    - apiVersion: v1
      kind: Service
      name: httpbin
      namespace: argo

    # RBAC (수정)
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      name: argo-role
      namespace: argo
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      name: agent
      namespace: argo
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      name: artifactgc
      namespace: argo
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      name: executor
      namespace: argo
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      name: pod-manager
      namespace: argo
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      name: submit-workflow-template
      namespace: argo
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      name: workflow-manager
      namespace: argo
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      name: argo-binding
      namespace: argo
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      name: agent-default
      namespace: argo
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      name: artifactgc-default
      namespace: argo
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      name: executor-default
      namespace: argo
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      name: github.com
      namespace: argo
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      name: pod-manager-default
      namespace: argo
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      name: workflow-manager-default
      namespace: argo

    # Deployments (유지)
    - apiVersion: apps/v1
      kind: Deployment
      name: workflow-controller
      namespace: argo
    - apiVersion: apps/v1
      kind: Deployment
      name: argo-server
      namespace: argo
    - apiVersion: apps/v1
      kind: Deployment
      name: minio
      namespace: argo
    - apiVersion: apps/v1
      kind: Deployment
      name: httpbin
      namespace: argo

  placement:
    clusterAffinity:
      clusterNames:
        - member1
    spreadConstraints:
      - maxGroups: 1
        minGroups: 1
        spreadByField: cluster
  propagationMode: BidirectionalSync
