apiVersion: policy.karmada.io/v1alpha1
kind: ClusterPropagationPolicy
metadata:
  name: argoevents-crds-policy
spec:
  resourceSelectors:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition  
      name: eventbus.argoproj.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: eventsources.argoproj.io 
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: sensors.argoproj.io
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      name: argo-events-role
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      name: argo-events-webhook
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      name: argo-events-aggregate-to-admin
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      name: argo-events-aggregate-to-edit
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      name: argo-events-aggregate-to-view
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      name: argo-events-binding
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      name: argo-events-webhook-binding

    # kube-system access 관련 Role 및 Binding 추가
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      name: kube-system-configmap-reader
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      name: kube-system-configmap-reader-binding

  placement:
    clusterAffinity:
      clusterNames:
        - member1
    
  placement:
    clusterAffinity:
      clusterNames:
        - member1
    spreadConstraints:
      - maxGroups: 1
        minGroups: 1
        spreadByField: cluster
  propagationMode: BidirectionalSync
