apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: argoevents-resources-policy
  namespace: argo-events
spec:
  resourceSelectors:
    # Namespace (Namespace가 반드시 먼저 배포되어야 함)
    - apiVersion: v1
      kind: Namespace
      name: argo-events

    # Core Resources (Namespace 범위 리소스)
    - apiVersion: v1
      kind: ServiceAccount
      name: argo-events-sa
      namespace: argo-events
    - apiVersion: v1
      kind: ServiceAccount
      name: argo-events-webhook-sa
      namespace: argo-events
    - apiVersion: v1
      kind: Secret
      name: webhook-tls-secret  # 필요한 경우 특정 Secret 지정
      namespace: argo-events
    - apiVersion: v1
      kind: Service
      name: events-webhook
      namespace: argo-events
    - apiVersion: v1
      kind: ConfigMap
      name: argo-events-controller-config
      namespace: argo-events

    # RBAC (Namespace 범위 Role 및 RoleBinding만 포함)
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      name: argo-events-role
      namespace: argo-events
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      name: argo-events-role-binding
      namespace: argo-events

    # Deployments (Argo Events 컨트롤러 및 Webhook)
    - apiVersion: apps/v1
      kind: Deployment
      name: controller-manager
      namespace: argo-events
    - apiVersion: apps/v1
      kind: Deployment
      name: events-webhook
      namespace: argo-events

    # Webhook Config
    - apiVersion: admissionregistration.k8s.io/v1
      kind: ValidatingWebhookConfiguration
      name: validating-webhook-configuration

    # EventBus (Argo Events 필수 리소스)
    - apiVersion: argoproj.io/v1alpha1
      kind: EventBus
      name: default
      namespace: argo-events

  placement:
    clusterAffinity:
      clusterNames:
        - member1
    spreadConstraints:
      - maxGroups: 1
        minGroups: 1
        spreadByField: cluster
  propagationMode: BidirectionalSync
