apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: argocd-crds-policy
  namespace: argocd
spec:
  resourceSelectors:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      labelSelector:
        matchLabels:
          app.kubernetes.io/part-of: argocd
  placement:
    clusterAffinity:
      clusterNames:
        - member1
