apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: argocd-policy
  namespace: argocd
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: Namespace
      name: argocd
    - apiVersion: apps/v1
      kind: Deployment
      namespace: argocd
    - apiVersion: v1
      kind: Service
      namespace: argocd
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
  placement:
    clusterAffinity:
      clusterNames:
        - member1
