apiVersion: policy.karmada.io/v1alpha1
kind: ClusterPropagationPolicy
metadata:
  name: argocd-crds-policy
spec:
  resourceSelectors:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      resourceNameSelector:  # resourceNames 대신 resourceNameSelector 사용
        matchExpressions:
          - operator: In
            values:
              - applications.argoproj.io
              - applicationsets.argoproj.io
              - appprojects.argoproj.io
          - operator: NotIn  # karmada CRD 제외
            values:
              - "*.karmada.io"
  placement:
    clusterAffinity:
      clusterNames:
        - member1
    spreadConstraints:
      - maxGroups: 1
        minGroups: 1
        spreadByField: cluster
  propagationMode: BidirectionalSync
