apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: argocd-crds-policy
  namespace: argocd
spec:
  resourceSelectors:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
  placement:
    clusterAffinity:
      clusterNames:
        - member1
    spreadConstraints:  # 추가
      - maxGroups: 1
        minGroups: 1
        spreadByField: cluster
  propagationMode: BidirectionalSync  # 추가
