apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: knative-istio-resources
  namespace: knative-serving
spec:
  resourceSelectors:
    # Istio CRDs (클러스터 전체에서 필요)
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: gateways.networking.istio.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: virtualservices.networking.istio.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: destinationrules.networking.istio.io
    # Istio ClusterRole & Binding (클러스터 전체에서 필요)
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      name: istio-admin
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      name: istio-admin-binding
  placement:
    clusterAffinity:
      clusterNames:
        - member1
  propagationMode: BidirectionalSync
