apiVersion: policy.karmada.io/v1alpha1
kind: ClusterPropagationPolicy
metadata:
  name: istio-cluster-resources
spec:
  resourceSelectors:
    # Istio CRDs
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: gateways.networking.istio.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: virtualservices.networking.istio.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: destinationrules.networking.istio.io

    # Istio Cluster Roles
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      name: istio-admin
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      name: istio-binding

  placement:
    clusterAffinity:
      clusterNames:
        - member1
  propagationMode: BidirectionalSync
