apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: knative-istio-resources
  namespace: knative-serving
spec:
  resourceSelectors:
      # Istio Namespace & Gateway
    - apiVersion: v1
      kind: Namespace
      name: istio-system
    - apiVersion: networking.istio.io/v1alpha3
      kind: Gateway
      name: knative-ingress-gateway
      namespace: istio-system

    # Istio VirtualService
    - apiVersion: networking.istio.io/v1alpha3
      kind: VirtualService
      name: knative-route
      namespace: istio-system
   placement:
    clusterAffinity:
      clusterNames:
        - member1
    spreadConstraints:
      - maxGroups: 1
        minGroups: 1
        spreadByField: cluster
  propagationMode: BidirectionalSync
