apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-webhook-secret-reader
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-webhook-secret-reader-binding
subjects:
  - kind: ServiceAccount
    name: cert-manager-webhook
    namespace: cert-manager
roleRef:
  kind: ClusterRole
  name: cert-manager-webhook-secret-reader
  apiGroup: rbac.authorization.k8s.io
